# **Импорт библиотек и подготовка**


In [ ]:
from matplotlib import pyplot as plt
import numpy as np
from sklearn.preprocessing import OneHotEncoder
import wrapt as wt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
contract = pd.read_csv("/content/drive/MyDrive/data_science/contract.csv")
internet =  pd.read_csv("/content/drive/MyDrive/data_science/internet.csv")
personal = pd.read_csv("/content/drive/MyDrive/data_science/personal.csv")
phone = pd.read_csv("/content/drive/MyDrive/data_science/phone.csv")


In [ ]:
contract

customerID   BeginDate              EndDate            Type  \
0     7590-VHVEG  2020-01-01                   No  Month-to-month   
1     5575-GNVDE  2017-04-01                   No        One year   
2     3668-QPYBK  2019-10-01  2019-12-01 00:00:00  Month-to-month   
3     7795-CFOCW  2016-05-01                   No        One year   
4     9237-HQITU  2019-09-01  2019-11-01 00:00:00  Month-to-month   
...          ...         ...                  ...             ...   
7038  6840-RESVB  2018-02-01                   No        One year   
7039  2234-XADUH  2014-02-01                   No        One year   
7040  4801-JZAZL  2019-03-01                   No  Month-to-month   
7041  8361-LTMKD  2019-07-01  2019-11-01 00:00:00  Month-to-month   
7042  3186-AJIEK  2014-08-01                   No        Two year   

     PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  
0                 Yes           Electronic check           29.85        29.85  
1                  No               Mailed check           56.95       1889.5  
2                 Yes               Mailed check           53.85       108.15  
3                  No  Bank transfer (automatic)           42.30      1840.75  
4                 Yes           Electronic check           70.70       151.65  
...               ...                        ...             ...          ...  
7038              Yes               Mailed check           84.80       1990.5  
7039              Yes    Credit card (automatic)          103.20       7362.9  
7040              Yes           Electronic check           29.60       346.45  
7041              Yes               Mailed check           74.40        306.6  
7042              Yes  Bank transfer (automatic)          105.65       6844.5  

[7043 rows x 8 columns]

In [ ]:
internet

customerID InternetService OnlineSecurity OnlineBackup DeviceProtection  \
0     7590-VHVEG             DSL             No          Yes               No   
1     5575-GNVDE             DSL            Yes           No              Yes   
2     3668-QPYBK             DSL            Yes          Yes               No   
3     7795-CFOCW             DSL            Yes           No              Yes   
4     9237-HQITU     Fiber optic             No           No               No   
...          ...             ...            ...          ...              ...   
5512  6840-RESVB             DSL            Yes           No              Yes   
5513  2234-XADUH     Fiber optic             No          Yes              Yes   
5514  4801-JZAZL             DSL            Yes           No               No   
5515  8361-LTMKD     Fiber optic             No           No               No   
5516  3186-AJIEK     Fiber optic            Yes           No              Yes   

     TechSupport StreamingTV StreamingMovies  
0             No          No              No  
1             No          No              No  
2             No          No              No  
3            Yes          No              No  
4             No          No              No  
...          ...         ...             ...  
5512         Yes         Yes             Yes  
5513          No         Yes             Yes  
5514          No          No              No  
5515          No          No              No  
5516         Yes         Yes             Yes  

[5517 rows x 8 columns]

**Объединим данных и разделение на категориальные признаки**

In [ ]:

# Объединение данных
data = pd.concat([contract, internet, personal, phone], axis=1)
data.to_csv('combined_data.csv', index=False)
# Разделение на числовые и категориальные признаки
numeric_features = data.select_dtypes(include=['float', 'int'])
categorical_features = data.select_dtypes(include=['object'])


# Разделение на числовые и категориальные признаки
numeric_features = data.select_dtypes(include=['float', 'int'])
categorical_features = data.select_dtypes(include=['object'])


In [ ]:
# Создаем экземпляр класса OneHotEncoder
encoder = OneHotEncoder()

# Применяем One-Hot Encoding к данным
encoded_A = encoder.fit_transform(categorical_features).toarray()

# Выводим преобразованный датасет
print(encoded_A)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [ ]:
scaler = StandardScaler()
scaled_d = scaler.fit_transform(numeric_features)

In [ ]:
preprocessed_data = pd.concat([pd.DataFrame(encoded_A), pd.DataFrame(scaled_d)], axis=1)

In [ ]:
target_variable = data['EndDate'].apply(lambda x: 1 if x == 'No' else 0)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(preprocessed_data, target_variable, test_size=0.2, random_state=42)

In [ ]:
# Создание и обучение модели логистической регрессии
logreg_model = LogisticRegression(multi_class='multinomial', solver='lbfgs')
logreg_model.fit(X_train, y_train)

# Предсказание на тестовой выборке
y_pred = logreg_model.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0
